name: flutter_bday
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter


  # External packages
  intl: ^0.20.2
  url_launcher: ^6.3.2 # to open WhatsApp with a message
  flutter_local_notifications: ^19.4.1
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.6.1
 # hive_ce_generator: ^1.8.2
  timezone: ^0.10.1
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator:
  build_runner:
flutter:
  uses-material-design: true
